---
title: "Insert Title Here"
author: '<span class="meta">Lemuel Kumarga</span>'
date: '<span class="meta">Mon YYYY</span>'
always_allow_html: yes
knit: (function(inputFile, encoding) { source("shared/knit.R"); knitPPT(inputFile, encoding) })
---

```{r echo=FALSE, warning=FALSE, results='hide'}
packages <- c("knitr")
tmp <- lapply(packages, library, character.only = TRUE)

# Set images globally
ou <- function(h_units) { 96 * h_units }
opts_chunk$set(fig.align='center', fig.height = 5, fig.width = 8,
               out.height= ou(5), out.width = ou(8), dpi = 300, echo=FALSE)
read_chunk("main.R")
```

```{r}
<<init>>
```

# Section Heading | Subtitle

## Default Deck

- <a data-toggle="popover" title="Lorem Ipsum" data-content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Data obtained from https://www.lipsum.com/.">Hover Point</a>
- Point 1
- Point 2
- Point 3

## Dark Deck { .slide-invert }

- <a data-toggle="popover" title="Lorem Ipsum" data-content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Data obtained from https://www.lipsum.com/.">Hover Point</a>
- Point 1
- Point 2
- Point 3

## Incremental Deck

>- <a data-toggle="popover" title="Lorem Ipsum" data-content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Data obtained from https://www.lipsum.com/.">Hover Point</a>
>- Point 1
>- Point 2
>- Point 3
